style(mysh): format scripts to use 4 spaces for indent

diff --git a/packages/mysh/.local/bin/next_ex b/packages/mysh/.local/bin/next_ex
--- a/packages/mysh/.local/bin/next_ex
+++ b/packages/mysh/.local/bin/next_ex
@@ -8,123 +8,123 @@ SRC_DIR="./src"
 declare -a EXCLUDE_LIST=()
 
 validate_current_directory() {
-  local dir_name
-  dir_name=$(basename "$CURRENT_DIR")
+    local dir_name
+    dir_name=$(basename "$CURRENT_DIR")
 
-  if [[ ! "$dir_name" =~ ^ex0([0-9])$ ]]; then
-    printf "Error: Current directory must be named ex0<[0-9]>\n" >&2
-    return 1
-  fi
-  if [[ ! -d "$SRC_DIR" ]]; then
-    printf "Error: src directory not found.\n" >&2
-    return 1
-  fi
+    if [[ ! "$dir_name" =~ ^ex0([0-9])$ ]]; then
+        printf "Error: Current directory must be named ex0<[0-9]>\n" >&2
+        return 1
+    fi
+    if [[ ! -d "$SRC_DIR" ]]; then
+        printf "Error: src directory not found.\n" >&2
+        return 1
+    fi
 
-  CURR_NB="${BASH_REMATCH[1]}"
-  return 0
+    CURR_NB="${BASH_REMATCH[1]}"
+    return 0
 }
 
 compute_next_directory() {
-  local next_nb
-  next_nb=$((CURR_NB + 1))
-  NEXT_DIR="../ex0${next_nb}/src"
-  return 0
+    local next_nb
+    next_nb=$((CURR_NB + 1))
+    NEXT_DIR="../ex0${next_nb}/src"
+    return 0
 }
 
 create_next_directory() {
-  mkdir -p "$NEXT_DIR" || {
-    printf "Error: Failed to create target directory: %s\n" "$NEXT_DIR" >&2
-    return 1
-  }
+    mkdir -p "$NEXT_DIR" || {
+        printf "Error: Failed to create target directory: %s\n" "$NEXT_DIR" >&2
+        return 1
+    }
 }
 
 is_excluded() {
-  local item="$1"
-  local name
-  name=$(basename "$item")
+    local item="$1"
+    local name
+    name=$(basename "$item")
 
-  for excluded in "${EXCLUDE_LIST[@]}"; do
-    if [[ "$name" == "$excluded" ]]; then
-      return 0
-    fi
-  done
+    for excluded in "${EXCLUDE_LIST[@]}"; do
+        if [[ "$name" == "$excluded" ]]; then
+            return 0
+        fi
+    done
 
-  return 1
+    return 1
 }
 
 copy_unique_items_to_next() {
-  local src_path dest_path rel_path
-  local -i copied=0
+    local src_path dest_path rel_path
+    local -i copied=0
 
-  shopt -s dotglob nullglob
-  for src_path in "$SRC_DIR"/* "$SRC_DIR"/.*; do
-    if [[ "$(basename "$src_path")" =~ ^\.\.?$ ]] || is_excluded "$src_path"; then
-      continue
-    fi
+    shopt -s dotglob nullglob
+    for src_path in "$SRC_DIR"/* "$SRC_DIR"/.*; do
+        if [[ "$(basename "$src_path")" =~ ^\.\.?$ ]] || is_excluded "$src_path"; then
+            continue
+        fi
 
-    rel_path="${src_path#"$SRC_DIR"/}"
-    dest_path="$NEXT_DIR/$rel_path"
+        rel_path="${src_path#"$SRC_DIR"/}"
+        dest_path="$NEXT_DIR/$rel_path"
 
-    if [[ -e "$dest_path" ]]; then
-      continue
-    fi
+        if [[ -e "$dest_path" ]]; then
+            continue
+        fi
 
-    if [[ -d "$src_path" ]]; then
-      cp -r "$src_path" "$dest_path" || {
-        printf "Error: Failed to copy directory: %s -> %s\n" "$src_path" "$dest_path" >&2
-        continue
-      }
-    else
-      cp -p "$src_path" "$dest_path" || {
-        printf "Error: Failed to copy file: %s -> %s\n" "$src_path" "$dest_path" >&2
-        continue
-      }
-    fi
-    ((copied++))
-  done
-  shopt -u dotglob nullglob
+        if [[ -d "$src_path" ]]; then
+            cp -r "$src_path" "$dest_path" || {
+                printf "Error: Failed to copy directory: %s -> %s\n" "$src_path" "$dest_path" >&2
+                continue
+            }
+        else
+            cp -p "$src_path" "$dest_path" || {
+                printf "Error: Failed to copy file: %s -> %s\n" "$src_path" "$dest_path" >&2
+                continue
+            }
+        fi
+        ((copied++))
+    done
+    shopt -u dotglob nullglob
 
-  printf "Copied %d new items to %s.\n" "$copied" "$NEXT_DIR"
+    printf "Copied %d new items to %s.\n" "$copied" "$NEXT_DIR"
 }
 
 change_directory() {
-  cd "$NEXT_DIR" || {
-    printf "Error: Failed to change to directory: %s\n" "$NEXT_DIR" >&2
-    return 1
-  }
+    cd "$NEXT_DIR" || {
+        printf "Error: Failed to change to directory: %s\n" "$NEXT_DIR" >&2
+        return 1
+    }
 }
 
 parse_arguments() {
-  local arg
+    local arg
 
-  while [[ $# -gt 0 ]]; do
-    arg="$1"
-    case "$arg" in
-    -e | --exclude)
-      shift
-      while [[ $# -gt 0 && "$1" != -* ]]; do
-        EXCLUDE_LIST+=("$(basename "$1")")
-        shift
-      done
-      ;;
-    -*)
-      printf "Error: Unknown option: %s\n" "$arg" >&2
-      return 1
-      ;;
-    *)
-      printf "Error: Unexpected argument: %s\n" "$arg" >&2
-      return 1
-      ;;
-    esac
-  done
+    while [[ $# -gt 0 ]]; do
+        arg="$1"
+        case "$arg" in
+        -e | --exclude)
+            shift
+            while [[ $# -gt 0 && "$1" != -* ]]; do
+                EXCLUDE_LIST+=("$(basename "$1")")
+                shift
+            done
+            ;;
+        -*)
+            printf "Error: Unknown option: %s\n" "$arg" >&2
+            return 1
+            ;;
+        *)
+            printf "Error: Unexpected argument: %s\n" "$arg" >&2
+            return 1
+            ;;
+        esac
+    done
 }
 main() {
-  parse_arguments "$@" || return 1
-  validate_current_directory || return 1
-  compute_next_directory || return 1
-  create_next_directory || return 1
-  copy_unique_items_to_next || return 1
-  change_directory || return 1
+    parse_arguments "$@" || return 1
+    validate_current_directory || return 1
+    compute_next_directory || return 1
+    create_next_directory || return 1
+    copy_unique_items_to_next || return 1
+    change_directory || return 1
 }
 
 main "$@"
diff --git a/packages/mysh/.local/bin/todo-list-interactiv b/packages/mysh/.local/bin/todo-list-interactiv
--- a/packages/mysh/.local/bin/todo-list-interactiv
+++ b/packages/mysh/.local/bin/todo-list-interactiv
@@ -15,225 +15,225 @@ declare -a DISPLAYED_INDEXES
 declare TODO_FILE
 
 get_indent_level() {
-  local line="$1"
-  local indent
-  indent=$(sed -E 's/^([[:space:]]*).*$/\1/' <<<"$line" | tr -dc ' ')
-  printf "%d" "${#indent}"
+    local line="$1"
+    local indent
+    indent=$(sed -E 's/^([[:space:]]*).*$/\1/' <<<"$line" | tr -dc ' ')
+    printf "%d" "${#indent}"
 }
 
 load_todo_file() {
-  local file="$1"
-  TODO_FILE="$file"
+    local file="$1"
+    TODO_FILE="$file"
 
-  local line
-  local index=0
-  local -a parent_stack=()
-  local -a indent_stack=()
+    local line
+    local index=0
+    local -a parent_stack=()
+    local -a indent_stack=()
 
-  while IFS= read -r line; do
-    RAW_LINES+=("$line")
+    while IFS= read -r line; do
+        RAW_LINES+=("$line")
 
-    local indent
-    indent=$(get_indent_level "$line")
-    local parent=""
-    while [[ ${#indent_stack[@]} -gt 0 && ${indent_stack[-1]} -ge $indent ]]; do
-      unset 'indent_stack[-1]'
-      unset 'parent_stack[-1]'
-    done
+        local indent
+        indent=$(get_indent_level "$line")
+        local parent=""
+        while [[ ${#indent_stack[@]} -gt 0 && ${indent_stack[-1]} -ge $indent ]]; do
+            unset 'indent_stack[-1]'
+            unset 'parent_stack[-1]'
+        done
 
-    if [[ ${#parent_stack[@]} -gt 0 ]]; then
-      parent="${parent_stack[-1]}"
-      CHILDREN["$parent"]+="$index "
-    fi
+        if [[ ${#parent_stack[@]} -gt 0 ]]; then
+            parent="${parent_stack[-1]}"
+            CHILDREN["$parent"]+="$index "
+        fi
 
-    indent_stack+=("$indent")
-    parent_stack+=("$index")
+        indent_stack+=("$indent")
+        parent_stack+=("$index")
 
-    if [[ $indent -lt 4 ]]; then
-      DISPLAYED_LINES+=("$line")
-      DISPLAYED_INDEXES+=("$index")
-    fi
+        if [[ $indent -lt 4 ]]; then
+            DISPLAYED_LINES+=("$line")
+            DISPLAYED_INDEXES+=("$index")
+        fi
 
-    ((index++))
-  done <"$file"
+        ((index++))
+    done <"$file"
 }
 
 toggle_checkbox_line() {
-  local index="$1"
-  local -n lines_ref="$2"
-  local line="${lines_ref[$index]}"
+    local index="$1"
+    local -n lines_ref="$2"
+    local line="${lines_ref[$index]}"
 
-  if [[ "$line" =~ ^([[:space:]]*)\[([ xX])\](.*)$ ]]; then
-    local prefix="${BASH_REMATCH[1]}"
-    local mark="${BASH_REMATCH[2]}"
-    local suffix="${BASH_REMATCH[3]}"
-    if [[ "$mark" == " " ]]; then
-      lines_ref[$index]="${prefix}[x]${suffix}"
-    else
-      lines_ref[$index]="${prefix}[ ]${suffix}"
+    if [[ "$line" =~ ^([[:space:]]*)\[([ xX])\](.*)$ ]]; then
+        local prefix="${BASH_REMATCH[1]}"
+        local mark="${BASH_REMATCH[2]}"
+        local suffix="${BASH_REMATCH[3]}"
+        if [[ "$mark" == " " ]]; then
+            lines_ref[$index]="${prefix}[x]${suffix}"
+        else
+            lines_ref[$index]="${prefix}[ ]${suffix}"
+        fi
     fi
-  fi
 }
 
 get_all_descendants() {
-  local index="$1"
-  local -a result=()
-  local child
+    local index="$1"
+    local -a result=()
+    local child
 
-  for child in ${CHILDREN[$index]}; do
-    result+=("$child")
-    result+=($(get_all_descendants "$child"))
-  done
+    for child in ${CHILDREN[$index]}; do
+        result+=("$child")
+        result+=($(get_all_descendants "$child"))
+    done
 
-  printf "%s\n" "${result[@]}"
+    printf "%s\n" "${result[@]}"
 }
 
 toggle_expand_collapse() {
-  local display_idx="$1"
-  local raw_idx="${DISPLAYED_INDEXES[$display_idx]}"
-  local -a new_lines=()
-  local -a new_indexes=()
+    local display_idx="$1"
+    local raw_idx="${DISPLAYED_INDEXES[$display_idx]}"
+    local -a new_lines=()
+    local -a new_indexes=()
 
-  if [[ -n "${EXPANDED[$raw_idx]}" ]]; then
-    # Collapse
-    local -A skip=()
-    for desc in $(get_all_descendants "$raw_idx"); do
-      skip["$desc"]=1
-    done
+    if [[ -n "${EXPANDED[$raw_idx]}" ]]; then
+        # Collapse
+        local -A skip=()
+        for desc in $(get_all_descendants "$raw_idx"); do
+            skip["$desc"]=1
+        done
 
-    for ((i = 0; i < ${#DISPLAYED_LINES[@]}; i++)); do
-      if [[ $i -eq $display_idx ]]; then
-        new_lines+=("${DISPLAYED_LINES[$i]}")
-        new_indexes+=("${DISPLAYED_INDEXES[$i]}")
-        continue
-      fi
+        for ((i = 0; i < ${#DISPLAYED_LINES[@]}; i++)); do
+            if [[ $i -eq $display_idx ]]; then
+                new_lines+=("${DISPLAYED_LINES[$i]}")
+                new_indexes+=("${DISPLAYED_INDEXES[$i]}")
+                continue
+            fi
 
-      if [[ -z "${skip[${DISPLAYED_INDEXES[$i]}]}" ]]; then
-        new_lines+=("${DISPLAYED_LINES[$i]}")
-        new_indexes+=("${DISPLAYED_INDEXES[$i]}")
-      fi
-    done
+            if [[ -z "${skip[${DISPLAYED_INDEXES[$i]}]}" ]]; then
+                new_lines+=("${DISPLAYED_LINES[$i]}")
+                new_indexes+=("${DISPLAYED_INDEXES[$i]}")
+            fi
+        done
 
-    unset EXPANDED["$raw_idx"]
-  else
-    # Expand
-    local children="${CHILDREN[$raw_idx]}"
-    EXPANDED["$raw_idx"]=1
+        unset EXPANDED["$raw_idx"]
+    else
+        # Expand
+        local children="${CHILDREN[$raw_idx]}"
+        EXPANDED["$raw_idx"]=1
 
-    for ((i = 0; i <= display_idx; i++)); do
-      new_lines+=("${DISPLAYED_LINES[$i]}")
-      new_indexes+=("${DISPLAYED_INDEXES[$i]}")
-    done
+        for ((i = 0; i <= display_idx; i++)); do
+            new_lines+=("${DISPLAYED_LINES[$i]}")
+            new_indexes+=("${DISPLAYED_INDEXES[$i]}")
+        done
 
-    for child in $children; do
-      new_lines+=("${RAW_LINES[$child]}")
-      new_indexes+=("$child")
-    done
+        for child in $children; do
+            new_lines+=("${RAW_LINES[$child]}")
+            new_indexes+=("$child")
+        done
 
-    for ((i = display_idx + 1; i < ${#DISPLAYED_LINES[@]}; i++)); do
-      new_lines+=("${DISPLAYED_LINES[$i]}")
-      new_indexes+=("${DISPLAYED_INDEXES[$i]}")
-    done
-  fi
+        for ((i = display_idx + 1; i < ${#DISPLAYED_LINES[@]}; i++)); do
+            new_lines+=("${DISPLAYED_LINES[$i]}")
+            new_indexes+=("${DISPLAYED_INDEXES[$i]}")
+        done
+    fi
 
-  DISPLAYED_LINES=("${new_lines[@]}")
-  DISPLAYED_INDEXES=("${new_indexes[@]}")
+    DISPLAYED_LINES=("${new_lines[@]}")
+    DISPLAYED_INDEXES=("${new_indexes[@]}")
 }
 
 menu() {
-  local -n options_ref=$1
-  local selected=0
-  local c
-  local hilight="${ESC}[${UD};${ESC}[1;${CYAN}m"
+    local -n options_ref=$1
+    local selected=0
+    local c
+    local hilight="${ESC}[${UD};${ESC}[1;${CYAN}m"
 
-  draw_menu() {
-    clear
-    printf "${hilight}File '$(basename -a -s '.todo' "$TODO_FILE")' todo list:${RESET}\n"
-    #printf "${hilight}TODO File Interactive Mode${RESET}\n"
-    printf "${ESC}[${IT};${BLACK}mUse ↑↓ to navigate, Space to toggle, Enter to expand/collapse, q to quit.${RESET}\n\n"
+    draw_menu() {
+        clear
+        printf "${hilight}File '$(basename -a -s '.todo' "$TODO_FILE")' todo list:${RESET}\n"
+        #printf "${hilight}TODO File Interactive Mode${RESET}\n"
+        printf "${ESC}[${IT};${BLACK}mUse ↑↓ to navigate, Space to toggle, Enter to expand/collapse, q to quit.${RESET}\n\n"
 
-    for ((i = 0; i < ${#options_ref[@]}; i++)); do
-      local line="${options_ref[$i]}"
-      local raw_index="${DISPLAYED_INDEXES[$i]}"
+        for ((i = 0; i < ${#options_ref[@]}; i++)); do
+            local line="${options_ref[$i]}"
+            local raw_index="${DISPLAYED_INDEXES[$i]}"
 
-      if [[ $i -eq $selected ]]; then
-        if [[ -n "${CHILDREN[$raw_index]}" ]]; then
-          printf "${ESC}[7m>  %s${RESET}\n" "$line"
-        else
-          printf "${ESC}[7m> %s${RESET}\n" "$line"
-        fi
-      else
-        if [[ -n "${CHILDREN[$raw_index]}" ]]; then
-          printf " %s\n" "$line"
-        else
-          printf "  %s\n" "$line"
-        fi
-      fi
+            if [[ $i -eq $selected ]]; then
+                if [[ -n "${CHILDREN[$raw_index]}" ]]; then
+                    printf "${ESC}[7m>  %s${RESET}\n" "$line"
+                else
+                    printf "${ESC}[7m> %s${RESET}\n" "$line"
+                fi
+            else
+                if [[ -n "${CHILDREN[$raw_index]}" ]]; then
+                    printf " %s\n" "$line"
+                else
+                    printf "  %s\n" "$line"
+                fi
+            fi
+        done
+    }
+
+    stty -icanon -echo
+    trap 'stty sane; clear; exit 1' INT TERM
+
+    while true; do
+        draw_menu
+        IFS= read -rsn1 c
+        case "$c" in
+        $'\x1b')
+            IFS= read -rsn2 -t 0.01 rest
+            case "$rest" in
+            "[A") selected=$(((selected - 1 + ${#options_ref[@]}) % ${#options_ref[@]})) ;;
+            "[B") selected=$(((selected + 1) % ${#options_ref[@]})) ;;
+            *)
+                stty sane
+                return 0
+                ;;
+            esac
+            ;;
+        " ")
+            toggle_checkbox_line "${DISPLAYED_INDEXES[$selected]}" RAW_LINES
+            DISPLAYED_LINES[$selected]="${RAW_LINES[${DISPLAYED_INDEXES[$selected]}]}"
+            ;;
+        "") # ENTER
+            toggle_expand_collapse "$selected"
+            ;;
+        "q" | "Q")
+            stty sane
+            return 0
+            ;;
+        esac
     done
-  }
-
-  stty -icanon -echo
-  trap 'stty sane; clear; exit 1' INT TERM
-
-  while true; do
-    draw_menu
-    IFS= read -rsn1 c
-    case "$c" in
-    $'\x1b')
-      IFS= read -rsn2 -t 0.01 rest
-      case "$rest" in
-      "[A") selected=$(((selected - 1 + ${#options_ref[@]}) % ${#options_ref[@]})) ;;
-      "[B") selected=$(((selected + 1) % ${#options_ref[@]})) ;;
-      *)
-        stty sane
-        return 0
-        ;;
-      esac
-      ;;
-    " ")
-      toggle_checkbox_line "${DISPLAYED_INDEXES[$selected]}" RAW_LINES
-      DISPLAYED_LINES[$selected]="${RAW_LINES[${DISPLAYED_INDEXES[$selected]}]}"
-      ;;
-    "") # ENTER
-      toggle_expand_collapse "$selected"
-      ;;
-    "q" | "Q")
-      stty sane
-      return 0
-      ;;
-    esac
-  done
 }
 
 save_changes() {
-  local tmp_file
-  if ! tmp_file=$(mktemp); then
-    printf "Error: Failed to create temporary file.\n" >&2
-    return 1
-  fi
+    local tmp_file
+    if ! tmp_file=$(mktemp); then
+        printf "Error: Failed to create temporary file.\n" >&2
+        return 1
+    fi
 
-  for line in "${RAW_LINES[@]}"; do
-    printf "%s\n" "$line"
-  done >"$tmp_file"
+    for line in "${RAW_LINES[@]}"; do
+        printf "%s\n" "$line"
+    done >"$tmp_file"
 
-  if ! mv -- "$tmp_file" "$TODO_FILE"; then
-    printf "Error: Failed to save changes to '%s'.\n" "$TODO_FILE" >&2
-    rm -f -- "$tmp_file"
-    return 1
-  fi
+    if ! mv -- "$tmp_file" "$TODO_FILE"; then
+        printf "Error: Failed to save changes to '%s'.\n" "$TODO_FILE" >&2
+        rm -f -- "$tmp_file"
+        return 1
+    fi
 }
 
 main() {
-  local file="$1"
+    local file="$1"
 
-  if [[ ! -f "$file" ]]; then
-    printf "Error: File '%s' not found.\n" "$file" >&2
-    return 1
-  fi
+    if [[ ! -f "$file" ]]; then
+        printf "Error: File '%s' not found.\n" "$file" >&2
+        return 1
+    fi
 
-  load_todo_file "$file"
-  menu DISPLAYED_LINES
-  save_changes
+    load_todo_file "$file"
+    menu DISPLAYED_LINES
+    save_changes
 }
 
 main "$@"
